// Dev-only fixture used to visually verify ReportCanvas without a live
// OpenAI key. Only wired in behind a NODE_ENV==='development' debug button
// on the chat page — never shipped as reachable production UI, and never
// used as a fallback for real /api/chat responses.
import type { ChatResponse } from "./types";

export const MOCK_CHAT_RESPONSE: ChatResponse = {
  conversation_id: "mock-conversation-1",
  message:
    "Here's your September sales performance report. Revenue is up versus August, driven mainly by the North region, though gross margin softened slightly.",
  intent: "ANALYSIS",
  report: {
    id: "mock-report-1",
    title: "September Sales Performance",
    subtitle: "Revenue, regional mix, and top customers — last 6 months",
    generated_by: "heuristic",
    kpis: [
      {
        id: "kpi_total_revenue",
        label: "Total Revenue",
        value: 508900,
        format: "currency",
        delta: 12.5,
        delta_label: "vs August",
        trend: "up",
        source_node_id: "n1",
      },
      {
        id: "kpi_gross_margin",
        label: "Gross Margin",
        value: 0.312,
        format: "percentage",
        delta: -2.1,
        delta_label: "vs August",
        trend: "down",
        source_node_id: "n1",
      },
      {
        id: "kpi_orders",
        label: "Total Orders",
        value: 271,
        format: "number",
        delta: 4.8,
        delta_label: "vs August",
        trend: "up",
        source_node_id: "n2",
      },
      {
        id: "kpi_avg_order_value",
        label: "Avg Order Value",
        value: 1878,
        format: "currency",
        delta: 0,
        delta_label: "flat vs August",
        trend: "flat",
        source_node_id: "n2",
      },
      {
        id: "kpi_overdue_invoices",
        label: "Overdue Invoices",
        value: 0.084,
        format: "percentage",
        delta: 1.6,
        delta_label: "vs August",
        trend: "up",
        source_node_id: "n2",
      },
    ],
    charts: [
      {
        id: "chart_revenue_trend",
        type: "line",
        title: "Revenue Trend",
        subtitle: "Last 6 months",
        data: [
          { month: "Apr", revenue: 412000 },
          { month: "May", revenue: 438500 },
          { month: "Jun", revenue: 401200 },
          { month: "Jul", revenue: 465800 },
          { month: "Aug", revenue: 452300 },
          { month: "Sep", revenue: 508900 },
        ],
        x_field: "month",
        y_field: "revenue",
        series: [{ name: "Revenue", field: "revenue" }],
        source_node_id: "n1",
      },
      {
        id: "chart_region_mix",
        type: "donut",
        title: "Revenue by Region",
        subtitle: "September",
        data: [
          { region: "North", revenue: 198500 },
          { region: "South", revenue: 132200 },
          { region: "East", revenue: 98700 },
          { region: "West", revenue: 79500 },
        ],
        x_field: "region",
        y_field: "revenue",
        series: [{ name: "Revenue", field: "revenue" }],
        source_node_id: "n2",
      },
      {
        id: "chart_deal_funnel",
        type: "funnel",
        title: "Sales Pipeline Conversion",
        subtitle: "September cohort",
        data: [
          { stage: "Leads", count: 1200 },
          { stage: "Qualified", count: 780 },
          { stage: "Proposal", count: 410 },
          { stage: "Negotiation", count: 205 },
          { stage: "Closed Won", count: 118 },
        ],
        x_field: "stage",
        y_field: "count",
        series: [{ name: "Count", field: "count" }],
        source_node_id: "n2",
      },
    ],
    tables: [
      {
        id: "table_top_customers",
        title: "Top Customers by Revenue",
        columns: [
          { field: "customer", label: "Customer", format: "text" },
          { field: "revenue", label: "Revenue", format: "currency" },
          { field: "order_count", label: "Orders", format: "number" },
        ],
        rows: [
          { customer: "Meridian Textiles", revenue: 89200, order_count: 14 },
          { customer: "Alpine Freight Co", revenue: 76500, order_count: 9 },
          { customer: "Solaris Retail Group", revenue: 68300, order_count: 11 },
          { customer: "Northwind Traders", revenue: 61100, order_count: 8 },
          { customer: "Beacon Manufacturing", revenue: 54200, order_count: 6 },
          { customer: "Crestview Holdings", revenue: 48900, order_count: 7 },
          { customer: "Harbor Point Supply", revenue: 41800, order_count: 5 },
          { customer: "Vantage Industries", revenue: 37600, order_count: 6 },
        ],
        source_node_id: "n3",
      },
      {
        id: "table_product_group_performance",
        title: "Product Group Performance",
        columns: [
          { field: "product_group", label: "Product Group", format: "text" },
          { field: "revenue", label: "Revenue", format: "currency" },
          { field: "growth_pct", label: "Growth %", format: "percentage" },
        ],
        rows: [
          { product_group: "Textiles", revenue: 142500, growth_pct: 8.4 },
          { product_group: "Electronics", revenue: 98700, growth_pct: -3.2 },
          { product_group: "Industrial Supplies", revenue: 76200, growth_pct: 12.1 },
          { product_group: "Packaging", revenue: 54300, growth_pct: -1.6 },
          { product_group: "Furniture", revenue: 41100, growth_pct: 0 },
        ],
        source_node_id: "n3",
      },
    ],
    insights: [
      {
        id: "i1",
        text: "Revenue grew 12.5% month-over-month, the strongest increase in the last 6 months, led by the North region.",
        kind: "headline",
      },
      {
        id: "i2",
        text: "Gross margin declined 2.1 points versus August, partly offsetting the revenue gain — worth checking discounting on large orders.",
        kind: "warning",
      },
      {
        id: "i3",
        text: "West region remains the smallest contributor at just 15.6% of total revenue — a potential growth opportunity.",
        kind: "warning",
      },
      {
        id: "i4",
        text: "Average order value was flat month-over-month, suggesting growth came from order volume rather than deal size.",
        kind: "note",
      },
    ],
    layout: [],
    query_trace: [
      {
        node_id: "n1",
        description: "Total revenue by month",
        sql: "SELECT strftime('%Y-%m', order_date) AS month, SUM(total_amount) AS revenue FROM sales_orders WHERE order_date >= date('now', '-6 months') GROUP BY month ORDER BY month",
        tables: ["sales_orders"],
        status: "success",
        row_count: 6,
        elapsed_ms: 42,
      },
      {
        node_id: "n2",
        description: "Revenue by region",
        sql: "SELECT r.name AS region, SUM(so.total_amount) AS revenue FROM sales_orders so JOIN customers c ON c.id = so.customer_id JOIN cities ci ON ci.id = c.city_id JOIN regions r ON r.id = ci.region_id GROUP BY r.name ORDER BY revenue DESC",
        tables: ["sales_orders", "customers", "cities", "regions"],
        status: "success",
        row_count: 4,
        elapsed_ms: 61,
      },
      {
        node_id: "n3",
        description: "Top customers by revenue",
        sql: "SELECT c.name AS customer, SUM(so.total_amount) AS revenue, COUNT(*) AS order_count FROM sales_orders so JOIN customers c ON c.id = so.customer_id GROUP BY c.name ORDER BY revenue DESC LIMIT 8",
        tables: ["sales_orders", "customers"],
        status: "success",
        row_count: 8,
        elapsed_ms: 38,
      },
    ],
  },
};
